#!/bin/bash
export LIBVIRT_DEFAULT_URI=${LIBVIRT_DEFAULT_URI:-qemu:///system}
vmname=$1
if [ -z "$vmname" ]
then
    virsh list
    echo "Usage: vm-crash <vmname>"
    exit 1
fi
echo "Will crash vm $vmname! Ctrl-C to cancel, enter to continue."
read dummy

virsh destroy "$vmname"
