#!/bin/bash
export LIBVIRT_DEFAULT_URI=${LIBVIRT_DEFAULT_URI:-qemu:///system}
vmname=$1
if [ -z "$vmname" ]
then
    virsh list --inactive
    echo "Usage: vm-start <vmname>"
    exit 1
fi

virsh start "$vmname"
